name: tests

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore
      run: dotnet restore BookBuddy.sln

    - name: Run tests
      run: dotnet test BookBuddy.Tests/BookBuddy.Tests.csproj --logger "trx;LogFileName=test.trx"

    - name: Test Reporter
      uses: dorny/test-reporter@v1
      with:
        name: tests
        path: "**/*.trx"
        reporter: dotnet-trx
